# Generated by Django 4.1.1 on 2022-11-03 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storyer', '0013_remove_assignment_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='storyer.group'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='questions_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='slides_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='video_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='zoom_link',
            field=models.URLField(blank=True),
        ),
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=25)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='storyer.faculty')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storyer.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='assigned_group', to='storyer.group'),
        ),
    ]
